# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0007_auto_20161130_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashitem',
            name='item_img',
            field=models.ImageField(blank=True, default='trash/images/notebook.png', null=True, upload_to=''),
        ),
    ]
