# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0008_auto_20161130_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashitem',
            name='item_img',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
