# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0011_itemrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashitem',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
